### ISSUE TITLE
Check composer.json autoloader

### ISSUE THREAD

**Issue by digitall-it** [lerni/folderindex#5]
Your composer.json autoloads the folder /folderindex mapping it to the App\ namespace, however there are just classes namespaced under Kraftausdruck\Extensions in that folder. I wonder if the composer.json would be more correct by putting Kraftausdruck\\ as a PSR-4 autoloading namespace or if everything is right and I didn't get how that works (very possible, indeed, and in that case, that would be an educative moment for me).

**Comment by lerni** [comment]
Ohh good catch! This really is wrong. Definitely a copy/past leftover - Silverstripes autoloader prevents bubbling up. It’s more of an optimization with Silverstripe not required. I’ll commit a fix.
